// tools/importer/import.js
// Auto-generated by /execute-aem-migration from knowledge-base/migration-plans/wknd-cloud-plan.md
// IMPORTANT: Validate CSS selectors against live AEM page source before running bulk import.
// .cmp-teaser selectors are assumed from standard AEM Core Components teaser markup —
// not yet confirmed against the real wknd-cloud author-rendered HTML (see plan Open Questions).

/* global WebImporter */

const CONTENT_ROOT = '/content/wknd-cloud';

function transformTeaser(cmp, isHero) {
  const rows = [[isHero ? 'teaser (hero)' : 'teaser']];

  const col0 = cmp.querySelector('.cmp-teaser__image picture, .cmp-teaser__image img')?.cloneNode(true) ?? '';

  const col1 = document.createElement('div');
  const title = cmp.querySelector('.cmp-teaser__title, .cmp-teaser__pretitle');
  if (title) {
    const h2 = document.createElement('h2');
    h2.innerHTML = title.innerHTML;
    col1.append(h2);
  }
  const description = cmp.querySelector('.cmp-teaser__description');
  if (description) {
    const p = document.createElement('p');
    p.innerHTML = description.innerHTML;
    col1.append(p);
  }
  const actionLinks = [...cmp.querySelectorAll('.cmp-teaser__action-link')];
  if (actionLinks.length) {
    const buttonPara = document.createElement('p');
    actionLinks.forEach((link, idx) => {
      const clone = link.cloneNode(true);
      const wrap = document.createElement(idx === 0 ? 'strong' : 'em');
      wrap.append(clone);
      buttonPara.append(wrap);
      if (idx < actionLinks.length - 1) buttonPara.append(' ');
    });
    col1.append(buttonPara);
  }

  rows.push([col0, col1]);
  cmp.replaceWith(WebImporter.DOMUtils.createTable(rows, document));
}

export default {
  transformDOM({ document: doc }) {
    // ── Remove chrome (auto-injected by EDS) ─────────────────────────────
    ['header', 'footer', 'nav',
      '.cmp-navigation', '.cmp-languagenavigation',
      '.cmp-search'].forEach((sel) => doc.querySelector(sel)?.remove());

    // ── teaser ─────────────────────────────────────────────────────────
    // Source: core/wcm/components/teaser/v3/teaser
    // Selector: .cmp-teaser
    const teasers = [...doc.querySelectorAll('.cmp-teaser')];
    teasers.forEach((cmp, idx) => transformTeaser(cmp, idx === 0));

    // ── Page metadata ─────────────────────────────────────────────────────
    const metaRows = [['metadata']];
    const title = doc.querySelector('h1')?.textContent.trim() || doc.title;
    metaRows.push(['title', title]);
    const desc = doc.querySelector('meta[name="description"]')?.content;
    if (desc) metaRows.push(['description', desc]);
    metaRows.push(['template', 'home']);
    doc.body.append(WebImporter.DOMUtils.createTable(metaRows, doc));

    return doc.body;
  },

  generateDocumentPath({ url }) {
    return new URL(url).pathname
      .replace(CONTENT_ROOT, '')
      .replace(/\.html$/, '');
  },
};
